tokyo = c[1019.4, 1005.7, 1002.0, 1006.7, 1005.1, 1010.1, 1016.7, 1011.0, 999.5, 1006.9,
1001.9, 1007.5, 1014.4, 1014.3, 1014.6, 1009.0, 1006.7, 1009.4, 1011.8, 1009.4]
tokyo = c(1019.4, 1005.7, 1002.0, 1006.7, 1005.1, 1010.1, 1016.7, 1011.0, 999.5, 1006.9,
1001.9, 1007.5, 1014.4, 1014.3, 1014.6, 1009.0, 1006.7, 1009.4, 1011.8, 1009.4)
view(tokyo)
library(tidyverse)
library(dplyr)
view(tokyo)
hukuoka = c(1018.4, 1007.6, 1006.2, 1009.9, 1010.8, 1013.2, 1016.2, 1009.1, 1003.1, 1012.5, 1006.4,
1006.3, 1012.2, 1015.0, 1017.4, 1016.5, 1012.1, 1008.7, 1009.2, 1009.2)
df <- data.frame(tokyo = tokyo, hukuoka_yesterday = hukuoka)
view(df)
write.csv(df, "1987_気象データ.csv", row.names=FALSE)
View(df)
plot(df['hukuoka_yesterday'], df['tokyo'])
df['hukuoka_yesterday']
c(df['hukuoka_yesterday'])
plot(c(df['hukuoka_yesterday']), c(df['tokyo']))
type(c(df['hukuoka_yesterday']))
is.vector(c(df['hukuoka_yesterday']))
df$tokyo
plot(df$hukuoka_yesterday, df$tokyo)
plot(df$hukuoka_yesterday, df$tokyo, xlim=c(1000, 1020), ylim=c(995, 1020), main = '福岡前日気圧と東京当日気圧',
xlab='前日の福岡の気圧', ylab='東京の気圧')
ad_df <- read.csv('advertising.csv')
view(ad_df)
length(ad_df)
nrow(ad_df)
par( mfrow = c(2, 2), mar=c(2, 2.5, 3, 1) + 0.1)
plot(ad_df$TV, ad_df$Sales, main='TV広告費と売上の関係')
plot(ad_df$Radio, ad_df$Sales, main='ラジオと売上の関係')
plot(ad_df$Newspaper, ad_df$Sales, main='新聞と売上の関係')
dev.off()
par( mfrow = c(2, 2), mar=c(2, 2.5, 3, 1) + 0.1)
plot(ad_df$TV, ad_df$Sales, main='TV広告費と売上の関係')
plot(ad_df$Radio, ad_df$Sales, main='ラジオと売上の関係')
plot(ad_df$Newspaper, ad_df$Sales, main='新聞と売上の関係')
par(mfrow=c(1, 1), mar=(2, 2.5, 3, 1) + 0.1)
par(mfrow=c(1, 1), mar=c(2, 2.5, 3, 1) + 0.1)
plot(ad_df$TV, ad_df$Sales, main='TV広告費と売上の関係')
log(ad_df$TV)
plot(log(ad_df$TV), log(ad_df$Sales), main='TV広告費と売上の関係_log')
m <- lm(ad_df$Sales, ad_df$TV)
m <- lm(ad_df$Sales ~ ad_df$TV)
m
m_log <- lm(log(ad_df$Sales), log(ad_df$TV) )
m_log <- lm(log(ad_df$Sales) ~ log(ad_df$TV) )
summary(m)
summary(m_log)
m_log_1 <- lm(ad_df$sales ~ log(ad_df$TV))
ad_df$Sales
lm(ad_df$Sales ~ log(ad_df$TV))
m_log_1 <- lm(ad_df$Sales ~ log(ad_df$TV))
summary(m_log_1)
plot(ad_df$TV, ad_df$Sales)
abline(m)
plot(ad_df$TV, ad_df$Sales, main='対数変換なし')
abline(m)
plot(log(ad_df$TV), log(ad_df$Sales), main='対数変換有')
abline(m_log)
plot(log(ad_df$TV), ad_df$Sales, main='説明変数のみ対数変換有')
abline(m_log_1)
m_log.predict()
predict(m_log)
glm()
m_poisson <- glm(ad_df$Sales ~ log(ad_df$TV), family = poisson(link = 'log'))
warnings()
summary(m_poisson)
pressure <- data(pressure)
view(pressure)
view(pressure)
data(pressure)
library(tidyverse)
library(dplyr)
data(pressure)
view(pressure)
data(cars)
view(cars)
View(pressure)
plot(pressure$temperature, pressure$pressure, main='温度と水銀の蒸気圧データ')
plot(cars$speed, cars$dist, main='自動車の速度と制動距離のデータ')
cars$dist^2
cars$dist
par(mfrow=c(2, 2), mar = c(2, 2.5, 3, 1) + 0.1)
plot(cars$speed, cars$dist)
plot(cars$speed, cars$dist^2)
plot(cars$speed, cars$dist^3)
plot(cars$speed, cars$dist^4)
plot(cars$speed, cars$dist)
plot(cars$speed^2, cars$dist)
plot(cars$speed^3, cars$dist)
plot(cars$speed^4, cars$dist)
par(mfrow=c(1, 1), mar =c(2, 2.5, 3, 1) + 0.1)
plot(pressure$temperature, pressure$pressure)
plot(pressure$temperature, log(pressure$pressure) )
par(mfrow(c(2, 2), mar = c(2, 2.5, 3, 1) + 1))
par(mfrow=c(2, 2), mar =c(2, 2.5, 3, 1) + 0.1)
plot(pressure$temperature, pressure$pressure)
plot(pressure$temperature, log(pressure$pressure) )
plot(pressure$temperature, log10(pressure$pressure) )
plot(pressure$temperature, log1p(pressure$pressure) )
par(mfrow=c(1, 1), mar =c(2, 2.5, 3, 1) + 0.1)
c_m <- lm(cars$dist ~ cars$speed)
c_m_square <- lm(cars$dist ~ cars$speed^2)
summary(c_m)
summary(c_m_square)
(cars$speed) ^2
cars$speed
c_m_square <- lm(cars$dist ~ (cars$speed)^2)
summary(c_m_square)
plot(cars$speed, cars$dist)
abline(c_m)
plot(cars$speed^2, cars$dist)
abline(c_m_square)
transform(cars, speed_square = cars$speed^2)
cars <- transform(cars, speed_square = cars$speed^2)
c_m_square <- lm(cars$dist ~ cars$speed_square)
summary(c_m)
summary(c_m_square)
plot(cars$speed_square, cars$dist)
abline(c_m_square)
# 何故か二乗がlmに反映されない
par(mfrow=c(1, 1), mar =c(2, 2.5, 3, 1) + 0.1)
p_m <- lm(pressure$pressure ~ pressure$temperature)
p_m_square <- lm(log(pressure$pressure) ~ pressure$temperature)
summary(p_m)
summary(p_m_square)
plot(pressure$temperature, pressure$pressure)
abline(p_m)
plot(pressure$temperature, log(pressure$pressure))
abline(p_m_square)
par(mfrow=c(1, 1), mar =c(2, 2.5, 3, 1) + 0.1)
plot()
plot(pressure$temperature, log(pressure$pressure))
abline(p_m_square)
View(cars)
View(c_m)
View(cars)
lm(dist ~ speed^2, data=cars)
abline(lm(dist ~ speed^2, data=cars))
plot(cars$speed, cars$dist)
abline(lm(dist ~ speed, data=cars))
abline(lm(dist ~ poly(speed,2), data=cars))
lm(dist ~ speed, data=cars)$r.squared
lm(dist ~ speed, data=cars)$adj.r.squared
lm(dist ~ speed, data=cars)
# 福岡と東京の回帰のテーブルを色々作っていく
view(df)
transform(df, hukuoka_same = c(df$tokyo))
df <- transform(df, hukuoka_same = c(df$tokyo))
view(df)
mean(df$tokyo)
tokyo_mean <- mean(df$tokyo)
hukuoka_mean <- mean(df$hukuoka_yesterday)
df <- transform(df, t_dev = c(df$tokyo - tokyo_mean))
view(df)
df <- transform(df, h_dev = c(df$hukuoka_yesterday - hukuoka_mean))
view(df)
df <- transform(df, t_dev_square = c(df$tokyo - tokyo_mean)^2 )
view(df)
df <- transform(df, h_dev_square = c(df$hukuoka_yesterday - hukuoka_mean)^2 )
view(df)
df <- transform(df, dev_sekiwa = c(df$hukuoka_yesterday - hukuoka_mean) * c(df$tokyo - tokyo_mean) )
view(df)
sum(df$dev_sekiwa)
coef_2 <- sum(df$dev_sekiwa) / sum(df$h_dev_square)
coef_1 <- mean(df$tokyo - (coef_2 * mean(df$hukuoka_yesterday) ))
lm(tokyo ~ hukuoka_yesterday, data=df)
lm_result <- lm(tokyo ~ hukuoka_yesterday, data=df)
lm_result_same <- lm(tokyo ~ hukuoka_same, data=df)
plot(df$hukuoka_yesterday, df$tokyo)
abline(lm_result)
abline(lm_result_same, lty = 'dotted')
summary(lm_result)
predict(lm_result)
df <- transform(df, tokyo_lm_result = predict(lm_result))
view(df)
df <- transform(df, residual = df$tokyo - df$tokyo_lm_result)
view8df
view(df)
sum(df$residual)
sum(df$residual * df$hukuoka_yesterday)
plot(df$hukuoka_yesterday, df$residual)
plot(df$residual)
s2 <- sum(df$residual^2 / (length(df) - 2) )
s2 <- sum(df$residual^2) / (length(df) - 2)
s2
s2 <- sum(df$residual^2 / (length(df) - 2) )
sum(df$residual^2)
length(df - 2)
nrow(df)
s2 <- sum(df$residual^2) / (nrow(df) - 2)
sqrt(s2)
s1 <- sqrt(s2)
abline(s2)
abline(h = s2)
abline(h = s1, lty= 'dotted')
abline(h = -s1, lth = 'dotted')
abline(h = -s1, lty = 'dotted')
abline(h = -s1, lty = 'dotted')
(df$tokyo  - tokyo_mean) / std(df$tokyo)
5 +5
(df$tokyo  - tokyo_mean) / std(df$tokyo)
(df$tokyo  - tokyo_mean) / sqrt(var(df$tokyo))
df <- transform(df, tokyo_normal = (df$tokyo  - tokyo_mean) / sqrt(var(df$tokyo)))
df <- transform(df, hukuoka_normal = (df$hukuoka_yesterday  - hukuoka_mean) / sqrt(var(df$hukuoka_yesterday)))
view(df)
lm_normal <- lm(tokyo_normal ~ hukuoka_normal, data=df)
summary(lm_normal)
correlate(df)
library(corrr)
correlate(df)
sum(df$tokyo_lm_result - tokyo_mean) / sum(df$tokyo - tokyo_mean)
sum(df$tokyo - tokyo_mean)
(sum(df$tokyo_lm_result - tokyo_mean)^2) / (sum(df$tokyo - tokyo_mean)^2)
sum(df$residual^2)
sum((df$tokyo - tokyo_mean) ^ 2)
1 - (178.4033 / 502.2095)
sum((df$tokyo_lm_result - tokyo_mean)^2) / sum((df$tokyo - tokyo_mean)^2)
savehistory("D:/R/20210327_ols_study/ols_study.R")
